package br.com.ucsal.simulado.util;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DatabaseUtil {

	
    private static final String URL = "jdbc:hsqldb:mem:testdb";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    public static void iniciarBanco() {
    	
        // Carrega a classe do driver JDBC do HSQLDB
        try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            stmt.executeUpdate("CREATE TABLE papel (" +
                               "id INT PRIMARY KEY, " +
                               "nome VARCHAR(50))");

            stmt.executeUpdate("CREATE TABLE usuario (" +
                               "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                               "nome VARCHAR(100), " +
                               "email VARCHAR(100), " +
                               "papel_id INT, " +
                               "FOREIGN KEY (papel_id) REFERENCES papel(id))");

            stmt.executeUpdate("INSERT INTO papel (id, nome) VALUES (1, 'Admin')");
            stmt.executeUpdate("INSERT INTO papel (id, nome) VALUES (2, 'User')");
            stmt.executeUpdate("INSERT INTO usuario (nome, email, papel_id) VALUES ('Pedro', 'renato@email.com', 1)");
            stmt.executeUpdate("INSERT INTO usuario (nome, email, papel_id) VALUES ('Maria', 'maria@email.com', 2)");

            System.out.println("Banco de dados inicializado com sucesso!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    
    
    
}

